version: '3.5'

services:
  redisdb:
    image: redis
    networks:
      - sentinet
    ports:
      - "6379"
  web:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_web
    networks:
      - sentinet
    ports:
      - "5000:5000"

networks:
    sentinet:
      name: sentinet
